### ISSUE TITLE
"Save" button not responding

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/bloomin-onion-client#48] opened 2018-02-01 21:46 UTC
Create new learning object
Put new outcomes
Hit "Save" 
It works only if, there is no assessment strategy. 
Nothing happens. 
Hit "Contribute"
Nothing happens. 
Hit "back to learning objects" 
It works, but the object is not saves completely. Goals is saved. First outcome is saved.

**Comment by siddharthkaza** [comment] 2018-02-05 20:01
Assuming the assessment and instructional strategies are removed from Beta then this issue is temporarily resolved.

**Comment by gshaw1997** [comment] 2018-02-05 22:23
@siddharthkaza Unable to reproduce issue pertaining to Outcomes' Assesment Plans/Instructional Strategies not saving.

**Comment by DonSeannelly** [comment] 2018-02-19 16:58
Closing for now as per 561d8d3b4249056539df5d2648a697df40d526c4 satisfying @siddharthkaza's comment.

**Closed by DonSeannelly** 2018-02-19 16:58 UTC
Labels: bug
