### ISSUE TITLE
Make the information button functional in Learning Outcomes

### ISSUE THREAD

**Issue by Jewel7** [Cyber4All/bloomin-onion-client#19] opened 2018-01-05 18:25 UTC
(Learning Object) Learning Outcomes — The “i” icon for information should list down information for that type of learning outcome. For example, clicking the “i” “Apply and Analyze” should tell the user what it is and what goal it’s trying to achieve, etc.

**Comment by KolbeML** [comment] 2018-01-05 20:32
Do we want to show the information on click or hover?

**Comment by DonSeannelly** [comment] 2018-01-08 14:28
@KolbeML I'm thinking maybe we do click, just in case someone is using this on mobile

**Comment by tylernhoward** [comment] 2018-01-08 16:50
Duplicate of Issue #4, Closing.

**Closed** 2018-01-08 16:50 UTC
Labels: feature request
